---
name: Check for lint/build errors

on:
  pull_request:
    branches:
      - main
  workflow_call:

jobs:
  lint:
    name: Lint Code Base, Spelling
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3

      - name: Lint
        uses: Consensys/docs-gha-2023/lint@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}a
